create table phone (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  phone text check (char_length(phone) > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table phone enable row level security;

create policy "Individuals can create their own phone." on phone for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view their own phone." on phone for
    select using (auth.uid() = user_id);

create policy "Individuals can update their own phone." on phone for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own phone." on phone for
    delete using (auth.uid() = user_id);
